carshop/config/routes.rb
Rails.application.routes.draw do

  root 'page#home'
 
  get 'page/about'

  get 'page/faqs'

  get 'page/contact'

end

carshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_action :set_product, only:  [:show, :edit, :update, :destroy]

#GET /products/1
#GET /products/1.json
def index
	@products=products.all
end


#GET /products/1
#GET /products/1.json
def show
end

carshop/app/helpers/application_helper.rb
module ApplicationHelper
end

carshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav id="nav">
	<div id="page_nav">
	/*
	* Son los botones de las diferentes paginas
	*/
		<%= link_to "Salir", root_path %>
		<%= link_to "Iniciar sesion", products_path %>
		<%= link_to "Registrarse", page_faqs_path %>
		<%= link_to "Contactos", page_contact_path %>
	</div>

		<div id="Iniciar Sesion">
			<% if user_signed_in? %>
				<%=  link_to "Salir", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Iniciar sesion", new_user_session_path %>
				<%= link_to "Registrarse", new_user_registration_path %>
			<%end%>
		</div>
</nav>
<div id="main_wrap">
			<p class="ntc"><%= notice %>
			<p class="alt"><%= alert %> 

	<%= yield %>
</div>
</body>
</html>